name: waka Readme 
on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Updated to the latest version

      - name: Update WakaTime Stats
        uses: anmol098/waka-readme-stats@master
        env:
          WAKATIME_API_KEY: waka_694f3cae-7f79-4a44-9e42-abf172d18c68
          GH_TOKEN: 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

      - name: Commit and Push if Changed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Updated WakaTime stats" || echo "No changes to commit"
          git push
